// WatchTower XDR - Agent Protocol Definition
// Phase: Faz 0.1 (gRPC Protocol Definition)
// Version: v0.1.0-alpha
//
// This file defines the gRPC contract between WT-Sentry/Interceptor agents
// and WT-Core (The Brain). All agent-to-core communication flows through
// this service over mTLS (port 50051).
//
// Usage:
//   protoc --go_out=. --go-grpc_out=. pkg/protocol/agent.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/protocol/agent.proto

package protocol

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────
//  AgentStatus
//  Enumerates the operational states Core can report back to an agent.
// ─────────────────────────────────────────────
type AgentStatus int32

const (
	// Default zero value; should never be used intentionally.
	// Treat as an error if received.
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	// Agent is healthy and operating normally.
	AgentStatus_AGENT_STATUS_OK AgentStatus = 1
	// Core has a new configuration version for this agent.
	// The agent should call the (future) ConfigFetch RPC to retrieve it.
	AgentStatus_AGENT_STATUS_CONFIG_UPDATE_PENDING AgentStatus = 2
	// The agent's mTLS certificate is nearing expiry (< 7 days remaining).
	// The agent should trigger certificate renewal immediately.
	AgentStatus_AGENT_STATUS_CERT_RENEWAL_REQUIRED AgentStatus = 3
	// Agent has been administratively disabled by an operator.
	// The agent should stop all monitoring activity and wait for re-enablement.
	AgentStatus_AGENT_STATUS_DISABLED AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_OK",
		2: "AGENT_STATUS_CONFIG_UPDATE_PENDING",
		3: "AGENT_STATUS_CERT_RENEWAL_REQUIRED",
		4: "AGENT_STATUS_DISABLED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED":           0,
		"AGENT_STATUS_OK":                    1,
		"AGENT_STATUS_CONFIG_UPDATE_PENDING": 2,
		"AGENT_STATUS_CERT_RENEWAL_REQUIRED": 3,
		"AGENT_STATUS_DISABLED":              4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_pkg_protocol_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{0}
}

// ─────────────────────────────────────────────
//  HeartbeatRequest
//  Sent by the agent to Core every 30 seconds.
// ─────────────────────────────────────────────
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// agent_id is the unique identifier assigned to this agent during
	// registration. Format: UUID v4 (e.g. "550e8400-e29b-41d4-a716-446655440000").
	// This field is mandatory; Core will reject requests with an empty agent_id.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// timestamp is the agent's local wall-clock time at the moment the
	// heartbeat is sent. Core stores this in the `agents.last_seen` column
	// and uses it to detect stale agents (timeout: 90 s).
	// Agents MUST populate this field.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ─────────────────────────────────────────────
//  HeartbeatResponse
//  Returned by Core to the agent after a successful heartbeat.
// ─────────────────────────────────────────────
type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status indicates the health / operational state acknowledged by Core.
	// Agents should log any status other than AGENT_STATUS_OK and alert
	// the operator if the state persists.
	Status AgentStatus `protobuf:"varint,1,opt,name=status,proto3,enum=watchtower.agent.v1.AgentStatus" json:"status,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

var File_pkg_protocol_agent_proto protoreflect.FileDescriptor

var file_pkg_protocol_agent_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x67, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x4d, 0x0a, 0x11, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0xab, 0x01, 0x0a, 0x0b, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x47, 0x45, 0x4e,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x41,
	0x47, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x47, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x26, 0x0a, 0x22, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x45, 0x52, 0x54, 0x5f, 0x52, 0x45, 0x4e, 0x45, 0x57, 0x41, 0x4c,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x41,
	0x47, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x41,
	0x42, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x32, 0x6a, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x12, 0x25, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x74, 0x6f, 0x77, 0x65, 0x72,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x45, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x31, 0x31, 0x2f, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x6f, 0x77, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_protocol_agent_proto_rawDescOnce sync.Once
	file_pkg_protocol_agent_proto_rawDescData = file_pkg_protocol_agent_proto_rawDesc
)

func file_pkg_protocol_agent_proto_rawDescGZIP() []byte {
	file_pkg_protocol_agent_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protocol_agent_proto_rawDescData)
	})
	return file_pkg_protocol_agent_proto_rawDescData
}

var file_pkg_protocol_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protocol_agent_proto_goTypes = []interface{}{
	(AgentStatus)(0),            // 0: watchtower.agent.v1.AgentStatus
	(*HeartbeatRequest)(nil),    // 1: watchtower.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 2: watchtower.agent.v1.HeartbeatResponse
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pkg_protocol_agent_proto_depIdxs = []int32{
	3, // 0: watchtower.agent.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: watchtower.agent.v1.HeartbeatResponse.status:type_name -> watchtower.agent.v1.AgentStatus
	1, // 2: watchtower.agent.v1.AgentService.Heartbeat:input_type -> watchtower.agent.v1.HeartbeatRequest
	2, // 3: watchtower.agent.v1.AgentService.Heartbeat:output_type -> watchtower.agent.v1.HeartbeatResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_protocol_agent_proto_init() }
func file_pkg_protocol_agent_proto_init() {
	if File_pkg_protocol_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protocol_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protocol_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_agent_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_agent_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_agent_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_agent_proto_msgTypes,
	}.Build()
	File_pkg_protocol_agent_proto = out.File
	file_pkg_protocol_agent_proto_rawDesc = nil
	file_pkg_protocol_agent_proto_goTypes = nil
	file_pkg_protocol_agent_proto_depIdxs = nil
}
